version: "3.9"
services:
  app:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgres://postgres:postgres@db:5432/cvapp
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      - ./apps/backend/uploads:/app/uploads
    ports:
      - "3000:3000"
